import React, { createContext, useContext, useState, useEffect, ReactNode, useMemo } from 'react';

export type Language = 'sw' | 'en' | 'zh' | 'ar' | 'fr' | 'pt';

export interface LanguageOption {
  code: Language;
  label: string;
  english: string;
  flag: string; // emoji flag
  dir: 'ltr' | 'rtl';
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'sw', label: 'Kiswahili', english: 'Swahili', flag: '🇹🇿', dir: 'ltr' },
  { code: 'en', label: 'English', english: 'English', flag: '🇬🇧', dir: 'ltr' },
  { code: 'zh', label: '中文', english: 'Chinese', flag: '🇨🇳', dir: 'ltr' },
  { code: 'ar', label: 'العربية', english: 'Arabic', flag: '🇸🇦', dir: 'rtl' },
  { code: 'fr', label: 'Français', english: 'French', flag: '🇫🇷', dir: 'ltr' },
  { code: 'pt', label: 'Português', english: 'Portuguese', flag: '🇵🇹', dir: 'ltr' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
  languages: LanguageOption[];
  current: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

type Dict = Record<string, string>;

const sw: Dict = {
  welcome: 'Karibu',
  welcome_kiduka: 'Karibu Kiduka',
  tagline: 'Biashara yako, urahisi wako',
  login_register: 'Ingia / Jisajili',
  visit_sokoni: 'Tembelea Sokoni',
  settings: 'Mipangilio',
  dashboard: 'Dashibodi',
  products: 'Bidhaa',
  sales: 'Mauzo',
  reports: 'Ripoti',
  customers: 'Wateja',
  users: 'Watumiaji',
  discounts: 'Punguzo',
  scanner: 'Skana',
  logout: 'Toka',
  profile_information: 'Taarifa za Wasifu',
  full_name: 'Jina Kamili',
  business_name: 'Jina la Biashara',
  email: 'Barua Pepe',
  update_profile: 'Sasisha Wasifu',
  security: 'Usalama',
  new_password: 'Nywila Mpya',
  confirm_password: 'Thibitisha Nywila',
  update_password: 'Sasisha Nywila',
  language_settings: 'Mipangilio ya Lugha',
  choose_language: 'Chagua Lugha',
  language_changed: 'Lugha imebadilishwa',
  theme_settings: 'Mipangilio ya Mandhari',
  dark_mode: 'Hali ya Giza',
  light_mode: 'Hali ya Mwanga',
  account_management: 'Usimamizi wa Akaunti',
  delete_account: 'Futa Akaunti',
  help_support: 'Msaada',
  help_center: 'Kituo cha Msaada',
  contact_support: 'Wasiliana na Msaada',
  save: 'Hifadhi',
  cancel: 'Ghairi',
  delete: 'Futa',
  confirm: 'Thibitisha',
  close: 'Funga',
  add: 'Ongeza',
  edit: 'Hariri',
  view: 'Angalia',
  export: 'Hamisha',
  success: 'Mafanikio',
  error: 'Hitilafu',
  loading: 'Inapakia...',
  no_data: 'Hakuna data',
  add_product: 'Ongeza Bidhaa',
  product_name: 'Jina la Bidhaa',
  price: 'Bei',
  stock: 'Hifadhi',
  category: 'Jamii',
  low_stock_alert: 'Onyo la Hifadhi Chini',
  total_sales: 'Jumla ya Mauzo',
  transactions: 'Miamala',
  daily_sales: 'Mauzo ya Kila Siku',
  payment_method: 'Njia ya Malipo',
  cash: 'Fedha Taslimu',
  card: 'Kadi',
  sales_report: 'Ripoti ya Mauzo',
  inventory_report: 'Ripoti ya Hifadhi',
  profit_analysis: 'Uchambuzi wa Faida',
  export_data: 'Hamisha Data',
  install_app: 'Sakinisha Kiduka',
  install_app_desc: 'Pata app kwenye simu yako kwa mbofyo mmoja',
  app_installed: 'Imesakinishwa',
  app_installed_desc: 'Kiduka ipo kwenye kifaa chako',
  installing: 'Inasakinisha...',
  install_manual_hint: 'Tumia menu ya browser kusakinisha',
  forgot_password: 'Sahau Nywila?',
  set_new_password: 'Weka Nywila Mpya',
  change_password: 'Badilisha Nywila',
  password_changed: 'Nywila imebadilishwa!',
  passwords_not_match: 'Nywila hazifanani',
  my_profile: 'Wasifu Wangu',
};

const en: Dict = {
  welcome: 'Welcome',
  welcome_kiduka: 'Welcome to Kiduka',
  tagline: 'Your business, made simple',
  login_register: 'Sign in / Sign up',
  visit_sokoni: 'Visit Sokoni',
  settings: 'Settings',
  dashboard: 'Dashboard',
  products: 'Products',
  sales: 'Sales',
  reports: 'Reports',
  customers: 'Customers',
  users: 'Users',
  discounts: 'Discounts',
  scanner: 'Scanner',
  logout: 'Logout',
  profile_information: 'Profile Information',
  full_name: 'Full Name',
  business_name: 'Business Name',
  email: 'Email',
  update_profile: 'Update Profile',
  security: 'Security',
  new_password: 'New Password',
  confirm_password: 'Confirm Password',
  update_password: 'Update Password',
  language_settings: 'Language Settings',
  choose_language: 'Choose Language',
  language_changed: 'Language changed',
  theme_settings: 'Theme Settings',
  dark_mode: 'Dark Mode',
  light_mode: 'Light Mode',
  account_management: 'Account Management',
  delete_account: 'Delete Account',
  help_support: 'Help & Support',
  help_center: 'Help Center',
  contact_support: 'Contact Support',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  confirm: 'Confirm',
  close: 'Close',
  add: 'Add',
  edit: 'Edit',
  view: 'View',
  export: 'Export',
  success: 'Success',
  error: 'Error',
  loading: 'Loading...',
  no_data: 'No data',
  add_product: 'Add Product',
  product_name: 'Product Name',
  price: 'Price',
  stock: 'Stock',
  category: 'Category',
  low_stock_alert: 'Low Stock Alert',
  total_sales: 'Total Sales',
  transactions: 'Transactions',
  daily_sales: 'Daily Sales',
  payment_method: 'Payment Method',
  cash: 'Cash',
  card: 'Card',
  sales_report: 'Sales Report',
  inventory_report: 'Inventory Report',
  profit_analysis: 'Profit Analysis',
  export_data: 'Export Data',
  install_app: 'Install Kiduka',
  install_app_desc: 'Get the app on your phone in one tap',
  app_installed: 'Installed',
  app_installed_desc: 'Kiduka is on your device',
  installing: 'Installing...',
  install_manual_hint: 'Use the browser menu to install',
  forgot_password: 'Forgot password?',
  set_new_password: 'Set New Password',
  change_password: 'Change Password',
  password_changed: 'Password changed!',
  passwords_not_match: 'Passwords do not match',
  my_profile: 'My Profile',
};

const zh: Dict = {
  welcome: '欢迎',
  welcome_kiduka: '欢迎使用 Kiduka',
  tagline: '让您的生意更简单',
  login_register: '登录 / 注册',
  visit_sokoni: '访问 Sokoni 商城',
  settings: '设置',
  dashboard: '仪表板',
  products: '产品',
  sales: '销售',
  reports: '报告',
  customers: '客户',
  users: '用户',
  discounts: '折扣',
  scanner: '扫描器',
  logout: '退出登录',
  profile_information: '个人资料',
  full_name: '全名',
  business_name: '商户名称',
  email: '电子邮箱',
  update_profile: '更新资料',
  security: '安全',
  new_password: '新密码',
  confirm_password: '确认密码',
  update_password: '更新密码',
  language_settings: '语言设置',
  choose_language: '选择语言',
  language_changed: '语言已更改',
  theme_settings: '主题设置',
  dark_mode: '深色模式',
  light_mode: '浅色模式',
  account_management: '账户管理',
  delete_account: '删除账户',
  help_support: '帮助与支持',
  help_center: '帮助中心',
  contact_support: '联系客服',
  save: '保存',
  cancel: '取消',
  delete: '删除',
  confirm: '确认',
  close: '关闭',
  add: '添加',
  edit: '编辑',
  view: '查看',
  export: '导出',
  success: '成功',
  error: '错误',
  loading: '加载中...',
  no_data: '暂无数据',
  add_product: '添加产品',
  product_name: '产品名称',
  price: '价格',
  stock: '库存',
  category: '类别',
  low_stock_alert: '库存不足提醒',
  total_sales: '总销售额',
  transactions: '交易',
  daily_sales: '每日销售',
  payment_method: '付款方式',
  cash: '现金',
  card: '银行卡',
  sales_report: '销售报告',
  inventory_report: '库存报告',
  profit_analysis: '利润分析',
  export_data: '导出数据',
  install_app: '安装 Kiduka',
  install_app_desc: '一键将应用安装到手机',
  app_installed: '已安装',
  app_installed_desc: 'Kiduka 已在您的设备上',
  installing: '安装中...',
  install_manual_hint: '请使用浏览器菜单安装',
  forgot_password: '忘记密码？',
  set_new_password: '设置新密码',
  change_password: '修改密码',
  password_changed: '密码已修改！',
  passwords_not_match: '两次密码不一致',
  my_profile: '我的资料',
};

const ar: Dict = {
  welcome: 'مرحبا',
  welcome_kiduka: 'مرحبا بك في كيدوكا',
  tagline: 'تجارتك، بكل بساطة',
  login_register: 'تسجيل الدخول / إنشاء حساب',
  visit_sokoni: 'زيارة سوكوني',
  settings: 'الإعدادات',
  dashboard: 'لوحة التحكم',
  products: 'المنتجات',
  sales: 'المبيعات',
  reports: 'التقارير',
  customers: 'العملاء',
  users: 'المستخدمون',
  discounts: 'الخصومات',
  scanner: 'الماسح',
  logout: 'تسجيل الخروج',
  profile_information: 'معلومات الملف الشخصي',
  full_name: 'الاسم الكامل',
  business_name: 'اسم النشاط التجاري',
  email: 'البريد الإلكتروني',
  update_profile: 'تحديث الملف',
  security: 'الأمان',
  new_password: 'كلمة مرور جديدة',
  confirm_password: 'تأكيد كلمة المرور',
  update_password: 'تحديث كلمة المرور',
  language_settings: 'إعدادات اللغة',
  choose_language: 'اختر اللغة',
  language_changed: 'تم تغيير اللغة',
  theme_settings: 'إعدادات المظهر',
  dark_mode: 'الوضع الداكن',
  light_mode: 'الوضع الفاتح',
  account_management: 'إدارة الحساب',
  delete_account: 'حذف الحساب',
  help_support: 'المساعدة والدعم',
  help_center: 'مركز المساعدة',
  contact_support: 'اتصل بالدعم',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',
  confirm: 'تأكيد',
  close: 'إغلاق',
  add: 'إضافة',
  edit: 'تعديل',
  view: 'عرض',
  export: 'تصدير',
  success: 'نجاح',
  error: 'خطأ',
  loading: 'جارٍ التحميل...',
  no_data: 'لا توجد بيانات',
  add_product: 'إضافة منتج',
  product_name: 'اسم المنتج',
  price: 'السعر',
  stock: 'المخزون',
  category: 'الفئة',
  low_stock_alert: 'تنبيه انخفاض المخزون',
  total_sales: 'إجمالي المبيعات',
  transactions: 'المعاملات',
  daily_sales: 'المبيعات اليومية',
  payment_method: 'طريقة الدفع',
  cash: 'نقدًا',
  card: 'بطاقة',
  sales_report: 'تقرير المبيعات',
  inventory_report: 'تقرير المخزون',
  profit_analysis: 'تحليل الأرباح',
  export_data: 'تصدير البيانات',
  install_app: 'تثبيت كيدوكا',
  install_app_desc: 'ثبّت التطبيق على هاتفك بضغطة واحدة',
  app_installed: 'مثبّت',
  app_installed_desc: 'كيدوكا موجود على جهازك',
  installing: 'جارٍ التثبيت...',
  install_manual_hint: 'استخدم قائمة المتصفح للتثبيت',
  forgot_password: 'نسيت كلمة المرور؟',
  set_new_password: 'تعيين كلمة مرور جديدة',
  change_password: 'تغيير كلمة المرور',
  password_changed: 'تم تغيير كلمة المرور!',
  passwords_not_match: 'كلمتا المرور غير متطابقتين',
  my_profile: 'ملفي الشخصي',
};

const fr: Dict = {
  welcome: 'Bienvenue',
  welcome_kiduka: 'Bienvenue sur Kiduka',
  tagline: 'Votre commerce, simplifié',
  login_register: 'Connexion / Inscription',
  visit_sokoni: 'Visiter Sokoni',
  settings: 'Paramètres',
  dashboard: 'Tableau de bord',
  products: 'Produits',
  sales: 'Ventes',
  reports: 'Rapports',
  customers: 'Clients',
  users: 'Utilisateurs',
  discounts: 'Remises',
  scanner: 'Scanner',
  logout: 'Déconnexion',
  profile_information: 'Informations du profil',
  full_name: 'Nom complet',
  business_name: "Nom de l'entreprise",
  email: 'E-mail',
  update_profile: 'Mettre à jour',
  security: 'Sécurité',
  new_password: 'Nouveau mot de passe',
  confirm_password: 'Confirmer le mot de passe',
  update_password: 'Mettre à jour le mot de passe',
  language_settings: 'Paramètres de langue',
  choose_language: 'Choisir la langue',
  language_changed: 'Langue modifiée',
  theme_settings: 'Paramètres du thème',
  dark_mode: 'Mode sombre',
  light_mode: 'Mode clair',
  account_management: 'Gestion du compte',
  delete_account: 'Supprimer le compte',
  help_support: 'Aide et support',
  help_center: "Centre d'aide",
  contact_support: 'Contacter le support',
  save: 'Enregistrer',
  cancel: 'Annuler',
  delete: 'Supprimer',
  confirm: 'Confirmer',
  close: 'Fermer',
  add: 'Ajouter',
  edit: 'Modifier',
  view: 'Voir',
  export: 'Exporter',
  success: 'Succès',
  error: 'Erreur',
  loading: 'Chargement...',
  no_data: 'Aucune donnée',
  add_product: 'Ajouter un produit',
  product_name: 'Nom du produit',
  price: 'Prix',
  stock: 'Stock',
  category: 'Catégorie',
  low_stock_alert: 'Alerte de stock faible',
  total_sales: 'Ventes totales',
  transactions: 'Transactions',
  daily_sales: 'Ventes quotidiennes',
  payment_method: 'Moyen de paiement',
  cash: 'Espèces',
  card: 'Carte',
  sales_report: 'Rapport de ventes',
  inventory_report: "Rapport d'inventaire",
  profit_analysis: 'Analyse des profits',
  export_data: 'Exporter les données',
  install_app: 'Installer Kiduka',
  install_app_desc: "Installez l'app sur votre téléphone en un clic",
  app_installed: 'Installée',
  app_installed_desc: 'Kiduka est sur votre appareil',
  installing: 'Installation...',
  install_manual_hint: 'Utilisez le menu du navigateur pour installer',
  forgot_password: 'Mot de passe oublié ?',
  set_new_password: 'Définir un nouveau mot de passe',
  change_password: 'Changer le mot de passe',
  password_changed: 'Mot de passe modifié !',
  passwords_not_match: 'Les mots de passe ne correspondent pas',
  my_profile: 'Mon profil',
};

const pt: Dict = {
  welcome: 'Bem-vindo',
  welcome_kiduka: 'Bem-vindo ao Kiduka',
  tagline: 'O seu negócio, simplificado',
  login_register: 'Entrar / Registar',
  visit_sokoni: 'Visitar Sokoni',
  settings: 'Definições',
  dashboard: 'Painel',
  products: 'Produtos',
  sales: 'Vendas',
  reports: 'Relatórios',
  customers: 'Clientes',
  users: 'Utilizadores',
  discounts: 'Descontos',
  scanner: 'Leitor',
  logout: 'Sair',
  profile_information: 'Informação do perfil',
  full_name: 'Nome completo',
  business_name: 'Nome do negócio',
  email: 'E-mail',
  update_profile: 'Atualizar perfil',
  security: 'Segurança',
  new_password: 'Nova palavra-passe',
  confirm_password: 'Confirmar palavra-passe',
  update_password: 'Atualizar palavra-passe',
  language_settings: 'Definições de idioma',
  choose_language: 'Escolher idioma',
  language_changed: 'Idioma alterado',
  theme_settings: 'Definições de tema',
  dark_mode: 'Modo escuro',
  light_mode: 'Modo claro',
  account_management: 'Gestão de conta',
  delete_account: 'Eliminar conta',
  help_support: 'Ajuda e suporte',
  help_center: 'Centro de ajuda',
  contact_support: 'Contactar suporte',
  save: 'Guardar',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  confirm: 'Confirmar',
  close: 'Fechar',
  add: 'Adicionar',
  edit: 'Editar',
  view: 'Ver',
  export: 'Exportar',
  success: 'Sucesso',
  error: 'Erro',
  loading: 'A carregar...',
  no_data: 'Sem dados',
  add_product: 'Adicionar produto',
  product_name: 'Nome do produto',
  price: 'Preço',
  stock: 'Stock',
  category: 'Categoria',
  low_stock_alert: 'Alerta de stock baixo',
  total_sales: 'Vendas totais',
  transactions: 'Transações',
  daily_sales: 'Vendas diárias',
  payment_method: 'Método de pagamento',
  cash: 'Dinheiro',
  card: 'Cartão',
  sales_report: 'Relatório de vendas',
  inventory_report: 'Relatório de inventário',
  profit_analysis: 'Análise de lucro',
  export_data: 'Exportar dados',
  install_app: 'Instalar Kiduka',
  install_app_desc: 'Instale a app no seu telemóvel num toque',
  app_installed: 'Instalada',
  app_installed_desc: 'O Kiduka está no seu dispositivo',
  installing: 'A instalar...',
  install_manual_hint: 'Use o menu do navegador para instalar',
  forgot_password: 'Esqueceu a palavra-passe?',
  set_new_password: 'Definir nova palavra-passe',
  change_password: 'Alterar palavra-passe',
  password_changed: 'Palavra-passe alterada!',
  passwords_not_match: 'As palavras-passe não coincidem',
  my_profile: 'O meu perfil',
};

const translations: Record<Language, Dict> = { sw, en, zh, ar, fr, pt };

const STORAGE_KEY = 'preferred-language';

const isLanguage = (value: string | null): value is Language =>
  !!value && LANGUAGES.some((l) => l.code === value);

const detectInitial = (): Language => {
  if (typeof window === 'undefined') return 'sw';
  const saved = localStorage.getItem(STORAGE_KEY);
  if (isLanguage(saved)) return saved;
  const nav = (navigator.language || 'sw').slice(0, 2).toLowerCase();
  if (isLanguage(nav)) return nav as Language;
  return 'sw';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(detectInitial);

  const current = useMemo(
    () => LANGUAGES.find((l) => l.code === language) || LANGUAGES[0],
    [language],
  );

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = current.dir;
  }, [language, current.dir]);

  const value = useMemo<LanguageContextType>(
    () => ({
      language,
      setLanguage,
      dir: current.dir,
      languages: LANGUAGES,
      current,
      t: (key: string) => translations[language]?.[key] ?? translations.en[key] ?? key,
    }),
    [language, current],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
