// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbjcuenvjrflfbdshogq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiamN1ZW52anJmbGZiZHNob2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNTMxNjEsImV4cCI6MjA3NDgyOTE2MX0.ZTxAEV2kt_RK9SL6JJK9g3ufKcYjDPaF2w6hU7MsXAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);