// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lufuusufaijuvekkcqgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZnV1c3VmYWlqdXZla2tjcWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDA4NTEsImV4cCI6MjA2MzkxNjg1MX0.mkyDOTXaBASR11vRJzLStcnUXxgZ1Z5ZfZSuOeY1NDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);